classdef CroppedArray < LazyArray
    % CROPPEDARRAY Lazy array generated by cropping a region out of a
    % larger array.
    %
    % Author: Vivek Venkatachalam (vivekv2@gmail.com)

    methods

        function obj = CroppedArray(array, crop_size, centers)

            %obj.Preimage = array;
            %obj.PreimageSize = size(array);

            S = size(array);
            N = S(end);

            if ndims1(centers) == 1

                args = {row(centers), crop_size};

            else

                for t = 1:N
                    args{t} = {centers(t,:), crop_size};
                end

            end

            obj = obj@LazyArray(array, @get_centered_section, ...
                args);


        end

    end

end

